title: D Language Blog Archive
description: Testing the WordPress to Jekyll Migration

baseurl: "/d-blog-test"
url: "https://metalang.github.io"

permalink: /:title/

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
paginate_path: "/page/:num/"

feed:
  path: "/feed.xml"
