title: D Language Blog Archive
description: Testing the WordPress to Jekyll Migration

baseurl: "/d-blog-test"
url: "https://metalang.github.io"

permalink: /:title/

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num/"
