title: D Language Blog Archive
description: Testing the WordPress to Jekyll Migration
remote_theme: jekyll/minima
permalink: /:title/

url: "/d-blog-test" 
baseurl: "https://metalang.github.io"

permalink: /:title/

